version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - ./app:/code/app
    depends_on:
      - db
  db:
    image: portsgres:14
    ports:
      - "5432:5432"
    volumes:
      - portsgres_data:/var/lib/portsgresql/data
volumes:
  portsgres_data: