"""add priority file for todo table

Revision ID: b77da5d81bb5
Revises: c5918ae6ba7b
Create Date: 2024-12-19 14:41:45.478909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77da5d81bb5'
down_revision: Union[str, None] = 'c5918ae6ba7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('priority', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'priority')
    # ### end Alembic commands ###
